@echo off
echo === Campaign Manager: Developer Install (Windows) ===

REM Create virtual environment
echo [1/6] Creating Python virtual environment...
python -m venv .venv

REM Activate it
call .venv\Scripts\activate

REM Install Python dependencies
echo [2/6] Installing Python packages...
pip install --upgrade pip
pip install -r requirements.txt
pip install pre-commit
pip install detect-secrets


REM Install Node packages
echo [3/6] Installing Node packages...
npm install

REM Setup .env file
REM I have no idea why it is using echo to send keys
REM TODO: fix the below autogenerated code

if not exist .env (
    echo [4/6] Creating .env file...
    echo OPENAI_API_KEY=your-key-here> .env
    echo GOOGLE_API_KEY=your-key-here>> .env
    echo OBS_WEBSOCKET_TOKEN=your-token-here>> .env
)

REM Setup pre-commit
echo [5/6] Setting up Git pre-commit hook...
pre-commit install

REM create baseline scan for detect-secrets
detect-secrets scan > .secrets.baseline

REM First pre-commit scan
pre-commit run --all-files
if %ERRORLEVEL% NEQ 0 (
    echo ❌ Pre-commit checks failed. Fix errors before continuing.
    exit /b 1
)

REM Test pre-commit manually

